#!/usr/bin/env bash

# Validate commit log
commit_regex='^Merge.+|(wip|release|feat|fix|polish|docs|style|refactor|perf|test|workflow|ci|chore|types|build|新增|修复|文档|样式|重构|优化|测试|打包|日常|回退|初始化)(\(.+\))?: .{1,50}'

if ! grep -iqE "$commit_regex" "$1"; then
    echo
    echo "  Error: proper commit message format is required for automated changelog generation."
    echo
    echo "  - Use \`npm run commit\` to interactively generate a commit message."
    echo "  - See .github/COMMIT_CONVENTION.md for more details."
    echo
    exit 1
fi
